### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by cmtonkinson** [forgecrafted/rulerz#12]
[Enter steps to reproduce below:]
1. Open a split pane
2. Drag and drop a file from one pane to the other

**Atom Version**: 0.210.0
**System**: linux 4.0.5-1-ARCH
**Thrown From**: [rulerz](https://github.com/forgecrafted/rulerz) package, v0.3.3
### Stack Trace

Uncaught TypeError: Cannot read property 'appendChild' of null

```
At /home/chris/repo/rulerz/lib/ruler-view.coffee:30

TypeError: Cannot read property 'appendChild' of null
    at ruler-view.RulerView.insert (/home/chris/repo/rulerz/lib/ruler-view.coffee:48:24)
    at ruler-view.RulerView.initialize (/home/chris/repo/rulerz/lib/ruler-view.coffee:31:12)
    at Object.createView (/home/chris/repo/rulerz/lib/ruler-manager.coffee:25:32)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app.asar/src/view-registry.js:74:72)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app.asar/src/view-registry.js:61:21)
    at CursorModel.module.exports.CursorModel.initialize (/home/chris/repo/rulerz/lib/cursor-model.coffee:25:25)
    at new CursorModel (/home/chris/repo/rulerz/lib/cursor-model.coffee:20:12)
    at /home/chris/repo/rulerz/lib/ruler-manager.coffee:33:20
    at TextEditor.module.exports.TextEditor.observeCursors (/usr/share/atom/resources/app.asar/src/text-editor.js:351:9)
    at /home/chris/repo/rulerz/lib/ruler-manager.coffee:32:49
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "autocomplete-plus",
      "autoflow",
      "encoding-selector",
      "metrics",
      "open-on-github",
      "snippets",
      "space-tab",
      "tabs-to-spaces",
      "timecop",
      "welcome",
      "ruby-block",
      "alignment",
      "file-types",
      "ruler",
      "hex",
      "atomic-number",
      "symbols-tree-view",
      "git-blame",
      "git-blame-plus",
      "wrap-guide",
      "multi-wrap-guide",
      "quotes"
    ],
    "themes": [
      "atom-dark-ui",
      "grandson-of-obsidian"
    ],
    "destroyEmptyPanes": false,
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.0.0
atom-alignment, v0.12.1
custom-title, v1.0.1
file-type-icons, v0.7.0
grandson-of-obsidian, v0.1.0
highlight-selected, v0.10.1
language-haml, v0.21.0
language-puppet, v0.12.0
language-rust, v0.4.3
language-salt, v0.4.0
minimap, v4.10.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
rulerz, v0.3.3

# Dev
No dev packages
```

**Comment by MichaelAquilina** [comment]
I just experienced the same issue on 

Ubuntu 14.10
Atom 1.0.11

**Comment by cmtonkinson** [comment]
I still haven't been able to figure this one out. It seems like Rulerz is initiating in the new pane before  `.scroll-view` exists, but I'm not sure how to fix that.
